/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mithusan Arulampalam
 */
//This application should prompt a user for an amount of money in dollars  
//and cents that he or she would like to exchange for coins

public class ChangeExchange extends javax.swing.JFrame {
    /**
     * Creates new form ChangeExchange
     */
    public ChangeExchange() {
        initComponents();
        //Makes only certain text field accessable to user
        AmountOutput.setEditable(false);
        QuartersOutput.setEditable(false);
        DimesOutput.setEditable(false);
        NickelsOutput.setEditable(false);
        PenniesOutput.setEditable(false);
        LooniesOutput.setEditable(false);
        TooniesOutput.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        CurrencyAmountInput = new javax.swing.JTextField();
        EnterCurrencyLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        ExitLabel = new javax.swing.JButton();
        CalculateLabel = new javax.swing.JButton();
        AmountOutput = new javax.swing.JTextField();
        AmountOutputLabel = new javax.swing.JLabel();
        QuartersLabel = new javax.swing.JLabel();
        PenniesLabel = new javax.swing.JLabel();
        LooniesLabel = new javax.swing.JLabel();
        TooniesLabel = new javax.swing.JLabel();
        NickelsLabel = new javax.swing.JLabel();
        DimesLabel = new javax.swing.JLabel();
        LooniesOutput = new javax.swing.JTextField();
        TooniesOutput = new javax.swing.JTextField();
        PenniesOutput = new javax.swing.JTextField();
        QuartersOutput = new javax.swing.JTextField();
        NickelsOutput = new javax.swing.JTextField();
        DimesOutput = new javax.swing.JTextField();
        ErrorOutput = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 0, 0));
        TitleLabel.setText("Change Exchange");

        CurrencyAmountInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyAmountInputActionPerformed(evt);
            }
        });

        EnterCurrencyLabel.setText("Enter Currency");

        AmountLabel.setText("Amount (xxxx.xx)");

        ExitLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ExitLabel.setText("Exit");
        ExitLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitLabelActionPerformed(evt);
            }
        });

        CalculateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CalculateLabel.setText("Calculate");
        CalculateLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateLabelActionPerformed(evt);
            }
        });

        AmountOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountOutputActionPerformed(evt);
            }
        });

        AmountOutputLabel.setText("Amount");

        QuartersLabel.setText("Quarters");

        PenniesLabel.setText("Pennies");

        LooniesLabel.setText("Loonies");

        TooniesLabel.setText("Toonies");

        NickelsLabel.setText("Nickels");

        DimesLabel.setText("Dimes");

        LooniesOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LooniesOutputActionPerformed(evt);
            }
        });

        TooniesOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TooniesOutputActionPerformed(evt);
            }
        });

        PenniesOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenniesOutputActionPerformed(evt);
            }
        });

        QuartersOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuartersOutputActionPerformed(evt);
            }
        });

        NickelsOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NickelsOutputActionPerformed(evt);
            }
        });

        DimesOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DimesOutputActionPerformed(evt);
            }
        });

        ErrorOutput.setForeground(new java.awt.Color(255, 0, 0));
        ErrorOutput.setText(" ");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DimesLabel)
                    .addComponent(QuartersLabel))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalculateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AmountLabel)
                                            .addComponent(EnterCurrencyLabel))
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(AmountOutputLabel)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(DimesOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(QuartersOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(9, 9, 9)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CurrencyAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AmountOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ExitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addComponent(ErrorOutput))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(NickelsLabel)
                                            .addGap(5, 5, 5))
                                        .addComponent(PenniesLabel))
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NickelsOutput)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(PenniesOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LooniesLabel)
                                        .addComponent(TooniesLabel))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LooniesOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                        .addComponent(TooniesOutput)))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TitleLabel)
                            .addGap(48, 48, 48))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnterCurrencyLabel)
                        .addGap(12, 12, 12)
                        .addComponent(AmountLabel)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(CurrencyAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ErrorOutput)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculateLabel)
                    .addComponent(ExitLabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountOutputLabel))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LooniesLabel)
                    .addComponent(LooniesOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NickelsLabel)
                    .addComponent(QuartersOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuartersLabel)
                    .addComponent(NickelsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TooniesOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TooniesLabel)
                    .addComponent(PenniesLabel)
                    .addComponent(PenniesOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DimesLabel)
                    .addComponent(DimesOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void CurrencyAmountInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrencyAmountInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrencyAmountInputActionPerformed

    private void ExitLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitLabelActionPerformed
        //Closes Program
        this.dispose();
        
    }//GEN-LAST:event_ExitLabelActionPerformed

    private void AmountOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountOutputActionPerformed

    private void LooniesOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LooniesOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LooniesOutputActionPerformed

    private void TooniesOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TooniesOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TooniesOutputActionPerformed

    private void PenniesOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenniesOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenniesOutputActionPerformed

    private void QuartersOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuartersOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuartersOutputActionPerformed

    private void NickelsOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NickelsOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NickelsOutputActionPerformed

    private void DimesOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DimesOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DimesOutputActionPerformed

    private void CalculateLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateLabelActionPerformed
        //Initalizes CurrencyInput
        double CurrencyInput = 0;
        
        //Prevents User from using Letters
        try {
            CurrencyInput = Double.parseDouble(CurrencyAmountInput.getText());//Checks Currency Input
        }
        catch(NumberFormatException e){//Checks if user inputs letters into Currency Input 
            ErrorOutput.setText("Numbers Only");//Error Output
        }
        //Output
        AmountOutput.setText(Double.toString(CurrencyInput));
        
        if (CurrencyInput >= 0.01){
            //Creates an Integer version of CurrencyInput (Double)
            int intCurrencyInput = (int) (CurrencyInput * 100);//Multiplys by 100 to get rid of decimals and make things easier

            //EQUATIONS
            //Divides *100 more accordingly
            //Calculates Amount of Toonies
            int Toonies = intCurrencyInput / 200; 

            //Calculates Amount of Loonies
            int Loonies = (intCurrencyInput - (200 * Toonies)) / 100;
            System.out.println(intCurrencyInput - (200 * Toonies));

            //Calculates Amount of Quarters
            int Quarters = (intCurrencyInput - (200 * Toonies) - (100 * Loonies)) / 25;    
            System.out.println(intCurrencyInput - (200 * Toonies) - (100 * Loonies));

            //Calculates Amount of Dimes
            int Dimes = (intCurrencyInput - (200 * Toonies) - (100 * Loonies) - (Quarters * 25)) / 10;
            System.out.println(intCurrencyInput - (200 * Toonies) - Loonies - (Quarters * 25));

            //Calculates Amount of Nickels
            int Nickels = (intCurrencyInput - (200 * Toonies) - (100 * Loonies) - (Quarters * 25) - (Dimes * 10)) / 5;
            System.out.println(intCurrencyInput - (200 * Toonies) - Loonies - (Quarters * 25) - (Dimes * 10));

            //Calculates Amount of Pennies
            int Pennies = (intCurrencyInput - (200 * Toonies) - (100 * Loonies) - (Quarters * 25) - (Dimes * 10) - (Nickels * 5)) / 1;
            System.out.println(intCurrencyInput - (200 * Toonies) - Loonies - (Quarters * 25) - (Dimes * 10) - (Nickels * 5));

            //OUTPUT
            TooniesOutput.setText(Integer.toString(Toonies));
            LooniesOutput.setText(Integer.toString(Loonies));
            QuartersOutput.setText(Integer.toString(Quarters));
            DimesOutput.setText(Integer.toString(Dimes));
            NickelsOutput.setText(Integer.toString(Nickels));
            PenniesOutput.setText(Integer.toString(Pennies));
        }
        else{
            ErrorOutput.setText("Positve Numbers Only");
        }
    }//GEN-LAST:event_CalculateLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeExchange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JTextField AmountOutput;
    private javax.swing.JLabel AmountOutputLabel;
    private javax.swing.JButton CalculateLabel;
    private javax.swing.JTextField CurrencyAmountInput;
    private javax.swing.JLabel DimesLabel;
    private javax.swing.JTextField DimesOutput;
    private javax.swing.JLabel EnterCurrencyLabel;
    private javax.swing.JLabel ErrorOutput;
    private javax.swing.JButton ExitLabel;
    private javax.swing.JLabel LooniesLabel;
    private javax.swing.JTextField LooniesOutput;
    private javax.swing.JLabel NickelsLabel;
    private javax.swing.JTextField NickelsOutput;
    private javax.swing.JLabel PenniesLabel;
    private javax.swing.JTextField PenniesOutput;
    private javax.swing.JLabel QuartersLabel;
    private javax.swing.JTextField QuartersOutput;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel TooniesLabel;
    private javax.swing.JTextField TooniesOutput;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
