/*
Programmer: Mithusan Arulampalam
Date: October 28th, 2019
Program Name: Student Grades
* Program Description: Student Grades Application that simulates a grade 
* book for a class with 15 students who each have four test scores with
* the use of a two-dimensional array
*/

//Imports
import java.util.ArrayList;
import java.util.regex.Pattern;

public class StudentGrades extends javax.swing.JFrame {
    //Variables that can Be used throught the Program
    double [][] mark = new double [15][4];//2D Array
    ArrayList<String> fullName = new ArrayList<>();//Arraylist
    ArrayList<String> Student = new ArrayList<>();//Arraylist
    ArrayList<String> studentAverage = new ArrayList<>();//Arraylist
    ArrayList<String> courseAverage1 = new ArrayList<>();//Arraylist
    ArrayList<String> courseAverage2 = new ArrayList<>();//Arraylist
    ArrayList<String> courseAverage3 = new ArrayList<>();//Arraylist
    ArrayList<String> courseAverage4 = new ArrayList<>();//Arraylist
    int row = 0;
    int i = 0;
    
    /**
     * Creates new form StudentGrades
     */
    public StudentGrades() {
        initComponents();
        //Disables Buttons
        ListButton.setEnabled(false);//List Button
        StudentAverage.setEnabled(false);//Student Average
        CourseAverage.setEnabled(false);//Course Average
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        FirstNameInput = new javax.swing.JTextField();
        LastNameInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Test1Input = new javax.swing.JTextField();
        Test2Input = new javax.swing.JTextField();
        Test3Input = new javax.swing.JTextField();
        Test4Input = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        StudentAverage = new javax.swing.JButton();
        CourseAverage = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextArea();
        ErrorOutput = new javax.swing.JTextField();
        ListButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AverageOutput = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(0, 0, 255));
        TitleLabel.setText("Student Grades");

        FirstNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        FirstNameLabel.setText("First Name: ");

        LastNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LastNameLabel.setText("Last Name: ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Test 1");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Test 3");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Test 2");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Test 4");

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        StudentAverage.setText("Student Average");
        StudentAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentAverageActionPerformed(evt);
            }
        });

        CourseAverage.setText("Course Average");
        CourseAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseAverageActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Output.setColumns(20);
        Output.setRows(5);
        jScrollPane1.setViewportView(Output);

        ErrorOutput.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ErrorOutput.setForeground(new java.awt.Color(255, 0, 0));

        ListButton.setText("List");
        ListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListButtonActionPerformed(evt);
            }
        });

        AverageOutput.setColumns(20);
        AverageOutput.setRows(5);
        jScrollPane2.setViewportView(AverageOutput);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLabel)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Test3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Test1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Test2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Test4Input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddButton)
                                            .addComponent(ListButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(StudentAverage)
                                            .addComponent(CourseAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 31, Short.MAX_VALUE)
                                        .addComponent(LastNameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ErrorOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(LastNameLabel)
                    .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Test1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(AddButton)
                    .addComponent(StudentAverage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Test2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CourseAverage)
                    .addComponent(ListButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Test3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Test4Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(ErrorOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        //TRY CATCH
        //Try
        try{
            //VARIABLES
            //Student Names
            String firstName = FirstNameInput.getText();//First Name of Student
            String lastName = LastNameInput.getText();//Last Name of Student
            
            //Test Marks
            double test1 = Double.parseDouble(Test1Input.getText());//First Test Mark 
            double test2 = Double.parseDouble(Test2Input.getText());//Second Test Mark
            double test3 = Double.parseDouble(Test3Input.getText());//Third Test Mark
            double test4 = Double.parseDouble(Test4Input.getText());//Forth Test Mark
            
            if(Pattern.matches("[a-zA-Z]+",firstName)){
                if(Pattern.matches("[a-zA-Z]+",lastName)){
                    if ((0 <= test1 && test1 <= 100) && (0 <= test2 && test2 <= 100) &&
                            (0 <= test3 && test3 <= 100) && (0 <= test4 && test4 <= 100)){
                        //Adds Student's full name to 'fullName' array to be later Used
                        fullName.add(firstName + " " + lastName);
                        
                        //Enables These options to be used if there is atleast one student
                        if (fullName.size() > 0){
                            StudentAverage.setEnabled(true);
                            CourseAverage.setEnabled(true);
                            
                            //Prevents IndexOutBoundsException
                            ListButton.setEnabled(true);
                        }
                        
                        //Adds Marks to the 2D Array
                        mark[row][0] = test1;//First Mark
                        mark[row][1] = test2;//Second Mark
                        mark[row][2] = test3;//Third Mark
                        mark[row][3] = test4;//Forth Mark

                        //Adds 1 to variable Row
                        //Prepares variable for next time user clicks add button
                        //Effects 2D array > Row
                        row++;
                        //Makes error output empty
                        ErrorOutput.setText("");
                    }//if ((0 <= test1 && test1 <= 100) && (0 <= test2 && test2 <= 100) 
                     //&& (0 <= test3 && test3 <= 100) && (0 <= test4 && test4 <= 100))
                    else{
                        //Error Output
                        ErrorOutput.setText("Please Enter a Mark from 0-100%");
                    }//End of else

                    //Runs code if Number of Students is equal to the maximum
                    //give amount of 15
                    if (fullName.size() == 15){
                            AddButton.setEnabled(false);//Disables ability to Add More Students
                            //Error Output
                            ErrorOutput.setText("You Have Reached the Maximum Amount of Students!");
                    }//if (fullName.size() == 15)
                    
                    //LIST BUTTON
                    //Adds To ArrayList to be Used Later
                    //Displays Students Fullname and all their marks
                    Student.add(fullName.get(i) + ":\n " + mark[i][0]+ "%, " + 
                           mark[i][1]+ "%, "+ mark[i][2]+ "%, "+ mark[i][3] + "%");
                    
                    //STUDENT AVERAGE BUTTON
                    studentAverage.add(fullName.get(i) + "\nhas a " + ((mark[i][0] + 
                            mark[i][1] + mark[i][2] + mark[i][3]) / 4) + "% average");
                    
                    courseAverage1.add(fullName.get(i) + ": " + mark[i][0] + "");
                    courseAverage2.add(fullName.get(i) + ": " + mark[i][1] + "");
                    courseAverage3.add(fullName.get(i) + ": " + mark[i][2] + "");
                    courseAverage4.add(fullName.get(i) + ": " + mark[i][3] + "");
                    
                    i++;
                    
                }//if(Pattern.matches("[a-zA-Z]+",lastName))
                else{
                    //Error Output
                    ErrorOutput.setText("Please only input letters for Names");   
                }//End of else
            }//if(Pattern.matches("[a-zA-Z]+",firstName))
            else{
                //Error Output
                ErrorOutput.setText("Please only input letters for Names");  
            }//End of else
        }//End of Try
        //Catch
        catch(NumberFormatException e){//Only accepts Numbers
            //Error Output
            ErrorOutput.setText("Please Input in Correct Format!");
        }//End of Catch
    }//GEN-LAST:event_AddButtonActionPerformed

    private void StudentAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentAverageActionPerformed
         //OUTPUT
        //Provides an alternative to String Class for Arraylist
        StringBuilder sb = new StringBuilder();
        for(String s : studentAverage){//for loop
            sb.append(s);
            sb.append("\n\n");//Spaces the List > Next Line
        }

        AverageOutput.setText(sb.toString());
    }//GEN-LAST:event_StudentAverageActionPerformed

    private void CourseAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseAverageActionPerformed
        double course1 = 0;
        double course2 = 0;
        double course3 = 0;
        double course4 = 0;
        
        for (int i = 0; i < fullName.size(); i++){
            course1 += mark[i][0];
            course2 += mark[i][1];
            course3 += mark[i][2];
            course4 += mark[i][3];
        }
        
        course1 = course1 / fullName.size();
        course2 = course2 / fullName.size();
        course3 = course3 / fullName.size();
        course4 = course4 / fullName.size();
        
        String RoundedCourse1 = String.format("%.2f", course1);
        String RoundedCourse2 = String.format("%.2f", course2);
        String RoundedCourse3 = String.format("%.2f", course3);
        String RoundedCourse4 = String.format("%.2f", course4);
        
        AverageOutput.setText("The Course Average for the first Course is:\n" + RoundedCourse1 + "%!\n" + courseAverage1 + "\n\n" +
               "The Course Average for the second Course is:\n" + RoundedCourse2 + "%!\n" + courseAverage2 + "\n\n" +
               "The Course Average for the third Course is:\n" + RoundedCourse3 + "%!\n" + courseAverage3 + "\n\n" +
               "The Course Average for the forth Course is:\n" + RoundedCourse4 + "%!\n" + courseAverage4);
    }//GEN-LAST:event_CourseAverageActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        //Closes Program
        this.dispose();
     
    }//GEN-LAST:event_ExitActionPerformed

    private void ListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListButtonActionPerformed
        //OUTPUT
        //Provides an alternative to String Class for Arraylist
        StringBuilder sb = new StringBuilder();
        for(String s : Student){//for loop
            sb.append(s);
            sb.append("\n\n");//Spaces the List > Next Line
        }

        Output.setText(sb.toString());
        
        //Prevents IndexOutBoundsException
        ListButton.setEnabled(false);
    }//GEN-LAST:event_ListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextArea AverageOutput;
    private javax.swing.JButton CourseAverage;
    private javax.swing.JTextField ErrorOutput;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField FirstNameInput;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField LastNameInput;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JButton ListButton;
    private javax.swing.JTextArea Output;
    private javax.swing.JButton StudentAverage;
    private javax.swing.JTextField Test1Input;
    private javax.swing.JTextField Test2Input;
    private javax.swing.JTextField Test3Input;
    private javax.swing.JTextField Test4Input;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
